config/routes.rb
Rails.application.routes.draw do

  get 'cards/show'
  resources :products

  resources :shops, only:[:index, :show]
  resources :order_items
  resources :cards, only:[:show]

  root'shops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :color
  belongs_to :product
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :assignments
  has_many :products, through: :assignments
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect{|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
  end

  private
  def set_subtotal
    self[:subtotal]= subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    unit_price*quantity
  end

  private
  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total*quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :assignments

  accepts_nested_attributes_for :assignments
  has_many :colors, through: :assignments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ApplicationHelper

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items= current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order= current_order
    @order_item= @order.order_items.new(order_params)
    @order.save
    session[:order_id]= @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

  private
  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @products= Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @product= Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cards/_card.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of #{current_order.subtotal }$", cards_path%>

app/views/cards/_cards_item.html.erb
<h1>Cards#show</h1>
<p>Find me in app/views/cards/show.html.erb</p>



<% @order_items.each do |item| %>

  <h3><%= item.product.title %></h3>
  <h5><%= item.product.price %></h5>


  <%= form_for item, remote: true do |f| %>



    <%= f.hidden_field :product_id, :value => item.product.id %>
    <%= f.number_field :quantity, :value => item.quantity.to_i %>
    <%= f.submit "Update Card "%>

    <%= link_to "Remove Items", order_item_path(item), method: :delete, remote: true%>

  <% end %>
  <h2>Subtotal: <%= item.total %></h2>

<% end %>




<h3>Your current card value has a subtotal of: <%= current_order.subtotal %></h3>

app/views/cards/show.html.erb
<div id="card-item">
  <%= render 'cards_item'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/create.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")

app/views/order_items/destroy.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item'))%>")

app/views/order_items/update.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item'))%>")

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>


  <% Color.all.each do |color| %>
    <%= form.fields_for :assignments do |f| %>
      <%= f.number_field :quantity %>
      <%= f.collection_select(:color_id, Color.all, :id, :color) %>

    <% end %>

  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<% @product.assignments.each do |a| %>
  <p>
    <%= a.color.color %> - <%= a.quantity %>
  </p>
<% end %>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shops/index.html.erb
<h1>Shops#index</h1>
<p>Find me in app/views/shops/index.html.erb</p>
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', shop_path(product) %></td>



      <td>


        <%= form_for @order_item, remote: true  do |f|%>
          <%= f.hidden_field :product_id, :value => product.id %>
          <%= f.number_field :quantity, :value => 1, :min =>  1%>
          <%= f.submit "Add to Card "%>


        <% end %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>

<br>
<div id="card">
  <%= render 'cards/card'%>
</div>

app/views/shops/show.html.erb
<h1>Shops#show</h1>
<p>Find me in app/views/shops/show.html.erb</p>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<% @product.assignments.each do |assignment| %>

  <%= assignment.color.color %>
  <%= assignment.quantity %>

<% end %>

<%= link_to 'Back', root_path %>